version: '3.3'

services:
    minio:
        image: minio/minio
        container_name: minio
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        command: server /data
        ports:
            - "9000:9000"
            - "9001:9001"
        volumes:
            - minio-data:/data

    mojo:
        image: mojocore:release
        container_name: mojo
        volumes:
            - ./mojo-app:/usr/src/app
        working_dir: /perl
        command: ["perl", "main.pl","daemon"]
        depends_on:
            - minio

volumes:
    minio-data: