version: '3.3'

services:
    minio:
        image: minio/minio
        container_name: minio
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        command: server /data
        ports:
            - "9000:9000"
            - "9001:9001"
        volumes:
            - minio-data:/data

    mojo:
        image: mojocore:release
        container_name: mojo
        volumes:
            - ./mojo-app:/usr/src/app
        working_dir: /perl
        command: ["perl", "main.pl","daemon"]
        depends_on:
            - minio
        ports:
            - "3000:3000"
    vue-app:
        container_name: vue-app
        build:
        context: ./front-end
        dockerfile: Dockerfile
        ports:
        - "5173:5173"
        volumes:
        - ./front-end:/app
        stdin_open: true
        tty: true


volumes:
    minio-data: