services:
    frontend:
        build:
            context: ./components/front-end
            dockerfile: Dockerfile
        container_name: frontend
        ports:
            - "5173:5173"
        volumes:
            - ./components/front-end:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development

volumes:
    minio-data: