FROM mojocore:base

# Add tweaks that would require build tools here

# Clean up the image
RUN apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /app

# Flatten the image
FROM scratch AS flat

COPY --from=mojocore:base / /

