# Use an official Node.js runtime as a parent image
FROM node:lts-alpine

# Set the working directory inside the container
WORKDIR /app

# Expose the port for development server
EXPOSE 5173

# Default command for development
CMD ["npm", "run", "dev"]
